export const GET_HOME_DATA_BEGIN = "GET_HOME_DATA_BEGIN";
export const GET_HOME_DATA_SUCESS = "GET_HOME_DATA_SUCESS";
export const GET_HOMEDATA_ERROR = "GET_HOME_DATA_ERROR";
export const GET_SINGLE_ALBUM_BEGIN = "GET_SINGLE_ALBUM_BEGIN";
export const GET_SINGLE_ALBUM_SUCESS = "GET_SINGLE_ALBUM_SUCESS";
export const GET_SINGLE_ALBUM_ERROR = "GET_SINGLE_ALBUM_ERROR";
export const PLAY_SONG_BEGIN = "PLAY_SONG_BEGIN";
export const PLAY_SONG_SUCESS = "PLAY_SONG_SUCESS";
export const PLAY_SONG_ERROR = "PLAY_SONG_ERROR";
export const SONG_PAUSED = "SONG_PAUSED";
export const SONG_PLAYING = "SONG_PLAYING";
export const RIGHT_MENU_BTN = "RIGHT_MENU_BTN";
export const SEARCH_BEGIN = "SEARCH_BEGIN";
export const SEARCH_SUCESS = "SEARCH_SUCESS";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const NEXT_PAGE_BTN = "NEXT_PAGE_BTN";
export const PREV_PAGE_BTN = "PREV_PAGE_BTN";
export const NEW_SEARCH_BEGIN = "NEW_SEARCH_BEGIN";
export const LEFT_MENU_BTN = "LEFT_MENU_BTN";
export const ALERT_SHOW = "ALERT_SHOW";
export const NEXT_SEARCHED_ARRAY = "NEXT_SEARCHED_ARRAY";
export const NEXT_SEARCHED_ARRAY_ERROR = "NEXT_SEARCHED_ARRAY_ERROR";
export const GET_SINGLE_PLAYLIST_BEGIN = "GET_SINGLE_PLAYLIST_BEGIN";
export const GET_SINGLE_PLAYLIST_SUCESS = "GET_SINGLE_PLAYLIST_SUCESS";
export const GET_SINGLE_PLAYLIST_ERROR = "GET_SINGLE_PLAYLIST_ERROR";
export const SEARCH_SONGS_SUCESS = "SEARCH_SONGS_SUCESS";
export const SEARCH_ALBUMS_SUCESS = "SEARCH_ALBUMS_SUCESS";
export const NEXT_SEARCHED_ALBUMS = "NEXT_SEARCHED_ALBUMS";
export const NEXT_PAGE_BTN_ALBUMS = "NEXT_PAGE_BTN_ALBUMS";
/////////////////////////////////////////////////////////
export const GET_ARTIST_DETAILS_BEGIN = "GET_ARTIST_DETAILS_BEGIN";
export const GET_ARTIST_DETAILS_SUCESS = "GET_ARTIST_DETAILS_SUCESS";
export const GET_ARTIST_DETAILS_ERROR = "GET_ARTIST_DETAILS_ERROR";
export const GET_ARTIST_SONGS_BEGIN = "GET_ARTIST_SONGS_BEGIN";
export const GET_ARTIST_SONGS_SUCESS = "GET_ARTIST_SONGS_SUCESS";
export const GET_ARTIST_SONGS_ERROR = "GET_ARTIST_SONGS_ERROR";
export const GET_ARTIST_ALBUMS_BEGIN = "GET_ARTIST_ALBUMS_BEGIN";
export const GET_ARTIST_ALBUMS_SUCESS = "GET_ARTIST_ALBUMS_SUCESS";
export const GET_ARTIST_ALBUMS_ERROR = "GET_ARTIST_ALBUMS_ERROR";
///////////////////////////////////////////////
export const USER_LOGIN_BEGIN = "USER_LOGIN_BEGIN";
export const USER_LOGIN_SUCESS = "USER_LOGIN_SUCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const LOGIN_FAILED_HANDLE = "LOGIN_FAILED_HANDLE";
/////////////////////////////////////////////////////////
export const USER_SIGNUP_BEGIN = "USER_SIGNUP_BEGIN";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED";
export const USER_SIGNUP_FINISHED = "USER_SIGNUP_FINISHED";
////////////////////////////////////////////////////////////
export const FORGOT_PASSWORD_BEGIN = "FORGOT_PASSWORD_BEGIN";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_SUCCUESS";
export const FORGOT_PASSWORD_FINISHED = "FORGOT_PASSWORD_FINISHED";
/////////////////////////////////////////////////////////////
export const AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS";
export const AUTO_LOGIN_FAILED = "AUTO_LOGIN_FAILED";

/////////////////////////
export const USER_DROP_DOWN_TOGGLE = "USER_DROP_DOWN_TOGGLE";
export const LOGOUT_USER_BEGIN = "LOGOUT_USER_BEGIN";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";

/////////////////////////////////////////////////////
export const USER_VERIFICATION = "USER_VERIFICATION";
export const USER_VERIFICATION_BEGIN = "USER_VERIFICATION_BEGIN";
export const USER_VERIFICATION_SUCCESS = "USER_VERIFICATION_SUCCESS";
export const USER_VERIFICATION_FAILED = "USER_VERIFICATION_FAILED";

/////////////////////// RESEND VERIFICATION SEND ////////////////////////
export const RESEND_VERIFICATION_BEGIN = "RESEND_VERIFICATION_BEGIN";
export const RESEND_VERIFICATION_SUCCESS = "RESEND_VERIFICATION_SUCCESS";
export const RESEND_VERIFICATAION_FAILED = "RESEND_VERIFICATION_FAILED";
